spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:    #开发环境
    name: servicecloud-config-dev
---
spring:
  profiles: test   #测试环境
  application:
    name: servicecloud-config-test
